language: cpp

env:
  global:
    - LINUX_DIST=trusty

matrix:
  include:
    - os: linux
      dist : bionic
      sudo : true
      compiler : gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - cmake

script:
  - gcc -v && g++ -v && cmake --version