language: cpp
compiler: gcc

os: linux
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - test/tester